/*monster project 2*/
Proc freq data= Mark.Birth;
tables area;
where area <5;
format area area.;
run;
proc freq data=Mark.Birth;
tables area;
run;
proc freq data=Mark.Birth;
Tables Area*sex;
run;
proc gchart data=Mark.Birth;
pie Area/discrete;
run;
proc SQL;
create table Mark.BirthTest	as
select * from Mark.birth left join Mark.death
on birth.crid=death.crid;
quit;
data Mark.Birth002;
set Mark.BirthTest;
length recorded_area $ 15;
if area <=4 then recorded_area = "Treatment";
else recorded_area = "Comparison";
AADM=(dod-dob)/30.46;
format aadm 6.2;
yob=year(dob);
mob=month(dob);
yod=year(dod);
mod=month(dod);
run;
proc ttest data=Mark.Birth002;
paired aadm*area;
run;
data Mark.Birth001;
set Mark.Birth002;
length Gender $8;
if sex = 1 then gender ="Male";
if sex = 2 then gender ="Female";
run;
data Mark.Treatment;
set Mark.Birth001;
where area <=4;
run;
data Mark.Comparison;
Set Mark.Birth001;
where area =5;
run;
Data Mark.Treatment1;
n=5;
P=2692;
do while (n <=358);
Slice=int (p*ranuni(-1));
set Mark.Treatment point=slice;
output;
n=n+1;
end;
stop;
run;
Data Mark.Comparison;
n=1;
P=4066;
do while (n <=391);
Slice=int (p*ranuni(-1));
set Mark.Comparison point=slice;
output;
n=n+1;
end;
stop;
run;
data Mark.CompTreat;
set Mark.Comparison Mark.Treatment1;
run;
proc freq data= Mark.CompTreat;
tables Gender*Recorded_area/chisq;
run;
